### ISSUE TITLE
Change Username to User's Display Name in rtMedia Activity

### ISSUE THREAD

**Issue by tecnich** [rtCamp/docs.rtcamp.com#11]
By default rtMedia uses user's nice name in activity. You can change it as per your requirement using the `rtmedia_buddypress_action_text_fitler` filter in your theme or plugin.

I am sure all users have nice names :-)

Do we want to say real name?

**Comment by tecnich** [comment]
Modified Appropriately.

**Comment by markob17** [comment]
Hi guys, I am not a coder by any means (can copy & paste well though!) and couldn't figure out how to change the nice name to the display name using the sample code on the rtmedia website. Can one of you guys help me out? That is the only change I would like to make. I would really appreciate it. Thanks!
