### ISSUE TITLE
License page updates

### ISSUE THREAD

**Issue by rahul286** [rtCamp/docs.rtcamp.com#13]
http://docs.rtcamp.com/license/

Page has old screenshots. Please update screenshots as well as activation flow.

**Comment by tecnich** [comment]
I checked the product with the existing licence documentation.

Except for the color of the Save Key button, the activation process is the
same.

I just activated addons on md.rtcamp.net.

What has changed exactly? Pointers will be helpful please.

Thanks
Michael

**Comment by rahul286** [comment]
I think this http://docs.rtcamp.com/wp-content/uploads/2014/09/Selection_013.png is different now.

They key-icon is not present in EDD addon. It was in WC addon. 

In any case, screenshot must be updated as well.

**Comment by tecnich** [comment]
The key is still present.

I have modified the screens appropriately.
