### ISSUE TITLE
Upgrading

### ISSUE THREAD

**Issue by tecnich** [rtCamp/docs.rtcamp.com#15]
The latest version of rtMedia is 3.7

Are these even valid any more:

* [Upgrading from rtMedia 3.2.x to 3.3.x](/rtmedia/upgrading/upgrading-rtmedia-3-2-to-3-3/)

	
* [Upgrading To rtMedia 3.5](/rtmedia/upgrading/upgrading-to-rtmedia-3-5/)

**Comment by nitun** [comment]
Not required that much but we can keep those two pages. Just for info to users who wants to know what things are changed from in those versions.

**Comment by rahul286** [comment]
@tecnich above links are broken. Provide correct links. 

I know correct links but its important to always paste correct link as habit.

**Comment by nitun** [comment]
http://docs.rtcamp.com/rtmedia/upgrading/upgrading-rtmedia-3-2-to-3-3/
http://docs.rtcamp.com/rtmedia/upgrading/upgrading-to-rtmedia-3-5/

--
Nitun Lanjewar | Product Head | rtCamp Solutions Pvt. Ltd.
Twitter: nitullanjewar | Web: http://rtcamp.com

**Comment by rahul286** [comment]
@nitun as said, I know links, the links in first comments are broken. 

@tecnich must know difference between relative and absolute URLs.

**Comment by nitun** [comment]
oh yes. I got it. 

Please @tecnich always provide links. I also search in entire docs or Google the same text to find out links. :|

**Comment by tecnich** [comment]
Sure will from next time. Sorry

**Comment by tecnich** [comment]
Cleaned up the doc and left it as is.
