### ISSUE TITLE
API Pages not found:

### ISSUE THREAD

**Issue by tecnich** [rtCamp/docs.rtcamp.com#18]
1. Media API: https://rtcamp.com/rtmedia/docs/developer/rtmedia-api/media-api
2.  API Core: https://rtcamp.com/rtmedia/docs/developer/rtmedia-api/api-core/
3. Media Endpoint: https://rtcamp.com/rtmedia/docs/developer/rtmedia-api/endpoints/media-endpoint

**Comment by rahul286** [comment]
Please check http://docs.rtcamp.com/rtmedia/developer/api/

**Comment by tecnich** [comment]
Yes and I just checked and the links on that page are wrong. That is why I
filed the bug.

What are the correct links?

**Comment by tecnich** [comment]
Any news on this folks?

**Comment by nitun** [comment]
I think those pages are missing. I checked in rtCamp.com, but not found.

@Ritesh, if you know correct links or pages, please share

--
Nitun Lanjewar | Product Head | rtCamp Solutions Pvt. Ltd.
Twitter: nitullanjewar | Web: http://rtcamp.com
