### ISSUE TITLE
Screenshots missing at http://docs.rtcamp.com/rtmedia/addons/rtmedia-pro/features/edit-media/

### ISSUE THREAD

**Issue by sumeetsarna** [rtCamp/docs.rtcamp.com#19]
Screenshots not visible  and numbering is not proper at http://docs.rtcamp.com/rtmedia/addons/rtmedia-pro/features/edit-media/

![selection_001](https://cloud.githubusercontent.com/assets/8191145/5753740/cb74f980-9cb3-11e4-8d06-b4f62f167a4a.png)

**Comment by tecnich** [comment]
Will check and fix.

**Comment by rahul286** [comment]
its markdown issue. I am fixing it.

**Comment by rahul286** [comment]
Fixed.

**Comment by rahul286** [comment]
@tecnich https://github.com/rtCamp/docs.rtcamp.com/commit/05212f58449e9f8662a9ec294e6660e5b2fee4bc

Please check my commit.

1. I fixed images links and removed wrapper anchor links. Extra `[![]`
2. Also, I removed unwanted spaces between list - https://github.com/rtCamp/docs.rtcamp.com/commit/05212f58449e9f8662a9ec294e6660e5b2fee4bc#diff-96898656077aff9a9b0c976ba347e33dL16

**Comment by tecnich** [comment]
Thanks Rahul.
