### ISSUE TITLE
Docs Clean up

### ISSUE THREAD

**Issue by sumeetsarna** [rtCamp/docs.rtcamp.com#20]
Links missing at http://docs.rtcamp.com/rtmedia/addons/rtmedia-pro/features/anywhere-gallery/

Screenshots missing at 1)http://docs.rtcamp.com/rtmedia/addons/rtmedia-pro/features/set-image-as-profile-picture/

2) http://docs.rtcamp.com/rtmedia/addons/rtmedia-pro/features/attach-media-to-activity-updates/

3)http://docs.rtcamp.com/rtmedia/addons/rtmedia-pro/features/media-albums-buddypress/

4) http://docs.rtcamp.com/rtmedia/addons/rtmedia-pro/features/set-a-default-thumbnail-for-videos/

5) http://docs.rtcamp.com/rtmedia/addons/rtmedia-pro/features/set-image-as-album-cover/

6) http://docs.rtcamp.com/rtmedia/addons/rtmedia-pro/features/set-media-featured/

7) Unncessary # @ http://docs.rtcamp.com/rtmedia/addons/rtmedia-pro/features/sidebar-widgets/

**Comment by tecnich** [comment]
Will check all the this and fix asap

**Comment by tecnich** [comment]
http://docs.rtcamp.com/rtmedia/docs/user/rtmedia-wordpress/anywhere-uploader/
is missing. What is the equivalent?

Rest are all fixed.

**Comment by rahul286** [comment]
I think
http://docs.rtcamp.com/rtmedia/features/shortcodes/uploader-shortcode/

Also make sure all shortcodes have single square brackets.

This `[[rtmedia_uploader]]` should be `[rtmedia_uploader]`.

Please do same for all shortcode. You may grep all .md files for "[["
locally. ;-)



--
Rahul Bansal | Founder & CEO
rtCamp Solutions Pvt. Ltd. | https://rtcamp.com/

**Comment by tecnich** [comment]
Thanks Rahul.

Will do.

Michael

**Comment by tecnich** [comment]
Done:-)
