### ISSUE TITLE
Source of this on Github?

### ISSUE THREAD

**Issue by tecnich** [rtCamp/docs.rtcamp.com#21]
In which gthub repo is https://rtcamp.com/rtmedia/docs/ stored? Please grant me access. I have manually verified what is missing in docs.rtcamp.com from there and want to add in the missing stuff. Thanks

**Comment by nitun** [comment]
https://rtcamp.com/rtmedia/docs/ its wordpress site, you can login to https://rtcamp.com/wp-admin/

Cross check and let me know..
