### ISSUE TITLE
Adding styles and scripts

### ISSUE THREAD

**Issue by priteshparmar1092** [rtCamp/docs.rtcamp.com#33]
I am trying to add style using rtp_head but its not working.

function custom_rtp_head() {
wp_enqueue_style( 'rt-assignment-foundation', get_template_directory_uri() . '/css/foundation/css/foundation.min.css', '', '5.5.1' );
}
add_action( 'rtp_head', 'custom_rtp_head' );

**Comment by sagarjadhav** [comment]
Hello priteshparmar1092,

Is this issue related to rtPanel? If so kindly create it here https://github.com/rtcamp/rtpanel

Thanks

**Comment by sagarjadhav** [comment]
Issue will discuss here https://github.com/rtCamp/rtpanel/issues/115
